import type { Deal } from "@/lib/types";

/**
 * Static demo deals shown when Demo Mode is enabled.
 * Covers a realistic mix of categories, big-box vs local, and Chicagoland shops.
 */

const now = new Date();
function hoursAgo(h: number): string {
  return new Date(now.getTime() - h * 3_600_000).toISOString();
}

export const DEMO_DEALS: Deal[] = [
  // Interspersed: big-box and local/small deals alternate for a natural feed feel
  {
    id: 9009,
    externalId: "demo-9",
    title: "Handmade Soy Candle Set — 3 for $25",
    description:
      "Locally poured soy candles in seasonal scents. Perfect gift bundles.",
    url: "#",
    imageUrl: null,
    price: 25.0,
    originalPrice: 42.0,
    store: "Wicker Park Candle Co.",
    source: "Demo",
    category: "retail",
    isBigBox: false,
    isChicagoland: true,
    publishedAt: hoursAgo(1),
    fetchedAt: hoursAgo(1),
    expiresAt: null,
  },
  {
    id: 9001,
    externalId: "demo-1",
    title: "Samsung 65\" 4K Smart TV — Clearance Price Drop",
    description:
      "Samsung Crystal UHD 65-inch on clearance at select locations. Limited stock while supplies last.",
    url: "#",
    imageUrl: null,
    price: 399.99,
    originalPrice: 549.99,
    store: "Best Buy",
    source: "Demo",
    category: "retail",
    isBigBox: true,
    isChicagoland: false,
    publishedAt: hoursAgo(1),
    fetchedAt: hoursAgo(1),
    expiresAt: null,
  },
  {
    id: 9018,
    externalId: "demo-18",
    title: "Full Synthetic Oil Change — $39.99 Special",
    description:
      "Includes up to 5 quarts of full synthetic oil, new filter, and 21-point inspection.",
    url: "#",
    imageUrl: null,
    price: 39.99,
    originalPrice: 69.99,
    store: "Mike's Auto Care",
    source: "Demo",
    category: "auto-service",
    isBigBox: false,
    isChicagoland: true,
    publishedAt: hoursAgo(2),
    fetchedAt: hoursAgo(2),
    expiresAt: null,
  },
  {
    id: 9002,
    externalId: "demo-2",
    title: "Dyson V15 Cordless Vacuum — $150 Off This Week",
    description:
      "The V15 Detect with laser dust detection is $150 off at Target through Sunday.",
    url: "#",
    imageUrl: null,
    price: 499.99,
    originalPrice: 649.99,
    store: "Target",
    source: "Demo",
    category: "retail",
    isBigBox: true,
    isChicagoland: false,
    publishedAt: hoursAgo(2),
    fetchedAt: hoursAgo(2),
    expiresAt: null,
  },
  {
    id: 9010,
    externalId: "demo-10",
    title: "Vintage Denim Jacket Collection — 40% Off All Styles",
    description:
      "Curated vintage denim from the 80s and 90s. Every jacket hand-picked and inspected.",
    url: "#",
    imageUrl: null,
    price: null,
    originalPrice: null,
    store: "Ragstock Chicago",
    source: "Demo",
    category: "retail",
    isBigBox: false,
    isChicagoland: true,
    publishedAt: hoursAgo(3),
    fetchedAt: hoursAgo(3),
    expiresAt: null,
  },
  {
    id: 9003,
    externalId: "demo-3",
    title: "DeWalt 20V MAX Drill/Driver Kit — Rollback",
    description:
      "Includes two batteries, charger, and carrying bag. Walmart rollback special.",
    url: "#",
    imageUrl: null,
    price: 89.0,
    originalPrice: 139.0,
    store: "Walmart",
    source: "Demo",
    category: "retail",
    isBigBox: true,
    isChicagoland: false,
    publishedAt: hoursAgo(3),
    fetchedAt: hoursAgo(3),
    expiresAt: null,
  },
  {
    id: 9011,
    externalId: "demo-11",
    title: "Artisan Leather Wallet — Small Batch Run",
    description:
      "Full-grain leather bifold made in small batches. Personalization available.",
    url: "#",
    imageUrl: null,
    price: 45.0,
    originalPrice: 65.0,
    store: "Oak & Anvil Leather",
    source: "Demo",
    category: "retail",
    isBigBox: false,
    isChicagoland: false,
    publishedAt: hoursAgo(4),
    fetchedAt: hoursAgo(4),
    expiresAt: null,
  },
  {
    id: 9006,
    externalId: "demo-6",
    title: "Apple AirPods Pro 2 — All-Time Low",
    description:
      "USB-C model with adaptive audio and conversation awareness. Lightning deal.",
    url: "#",
    imageUrl: null,
    price: 179.99,
    originalPrice: 249.99,
    store: "Amazon",
    source: "Demo",
    category: "retail",
    isBigBox: true,
    isChicagoland: false,
    publishedAt: hoursAgo(4),
    fetchedAt: hoursAgo(4),
    expiresAt: hoursAgo(-2), // expires in 2 hours
  },
  {
    id: 9019,
    externalId: "demo-19",
    title: "Brake Pad Replacement — Front or Rear $99",
    description:
      "Ceramic brake pads installed. Includes rotor inspection and brake fluid top-off.",
    url: "#",
    imageUrl: null,
    price: 99.0,
    originalPrice: 175.0,
    store: "Honest Wrench Garage",
    source: "Demo",
    category: "auto-service",
    isBigBox: false,
    isChicagoland: true,
    publishedAt: hoursAgo(4),
    fetchedAt: hoursAgo(4),
    expiresAt: null,
  },
  {
    id: 9012,
    externalId: "demo-12",
    title: "Kids' Summer Camp Gear Bundle — Everything They Need",
    description:
      "Backpack, water bottle, sunscreen, and bug spray combo deal at neighborhood shop.",
    url: "#",
    imageUrl: null,
    price: 34.99,
    originalPrice: 55.0,
    store: "Little Adventures",
    source: "Demo",
    category: "retail",
    isBigBox: false,
    isChicagoland: true,
    publishedAt: hoursAgo(5),
    fetchedAt: hoursAgo(5),
    expiresAt: null,
  },
  {
    id: 9004,
    externalId: "demo-4",
    title: "KitchenAid Stand Mixer — Spring Color Sale",
    description:
      "Classic 5-quart tilt-head stand mixer in seasonal colors. In-store and online.",
    url: "#",
    imageUrl: null,
    price: 279.99,
    originalPrice: 349.99,
    store: "Costco",
    source: "Demo",
    category: "retail",
    isBigBox: true,
    isChicagoland: false,
    publishedAt: hoursAgo(5),
    fetchedAt: hoursAgo(5),
    expiresAt: null,
  },
  {
    id: 9013,
    externalId: "demo-13",
    title: "Running Shoe Blowout — Last Season's Models 50% Off",
    description:
      "Brooks, Saucony, and New Balance from last season. All sizes while they last.",
    url: "#",
    imageUrl: null,
    price: null,
    originalPrice: null,
    store: "Fleet Feet Lincoln Park",
    source: "Demo",
    category: "retail",
    isBigBox: false,
    isChicagoland: true,
    publishedAt: hoursAgo(6),
    fetchedAt: hoursAgo(6),
    expiresAt: null,
  },
  {
    id: 9005,
    externalId: "demo-5",
    title: "Roundup Weed & Grass Killer 1-Gal — Buy One Get One",
    description: "BOGO deal on Roundup ready-to-use 1-gallon bottles. Garden center only.",
    url: "#",
    imageUrl: null,
    price: 14.98,
    originalPrice: 29.96,
    store: "Home Depot",
    source: "Demo",
    category: "retail",
    isBigBox: true,
    isChicagoland: false,
    publishedAt: hoursAgo(6),
    fetchedAt: hoursAgo(6),
    expiresAt: null,
  },
  {
    id: 9020,
    externalId: "demo-20",
    title: "AC Recharge & Inspection — Get Ready for Summer",
    description:
      "Full AC system check, refrigerant recharge, and leak test. Appointment required.",
    url: "#",
    imageUrl: null,
    price: 79.99,
    originalPrice: 129.99,
    store: "Cicero Auto Repair",
    source: "Demo",
    category: "auto-service",
    isBigBox: false,
    isChicagoland: true,
    publishedAt: hoursAgo(7),
    fetchedAt: hoursAgo(7),
    expiresAt: null,
  },
  {
    id: 9008,
    externalId: "demo-8",
    title: "Ninja Creami Ice Cream Maker — Lowest Price This Year",
    description: "Make ice cream, sorbet, and milkshakes at home. Limited stock.",
    url: "#",
    imageUrl: null,
    price: 149.99,
    originalPrice: 199.99,
    store: "Target",
    source: "Demo",
    category: "retail",
    isBigBox: true,
    isChicagoland: false,
    publishedAt: hoursAgo(7),
    fetchedAt: hoursAgo(7),
    expiresAt: null,
  },
  {
    id: 9007,
    externalId: "demo-7",
    title: "Weber Genesis Gas Grill — End of Season Clearance",
    description: "3-burner propane grill marked down for end of season. Floor models available.",
    url: "#",
    imageUrl: null,
    price: 649.0,
    originalPrice: 899.0,
    store: "Lowe's",
    source: "Demo",
    category: "retail",
    isBigBox: true,
    isChicagoland: false,
    publishedAt: hoursAgo(8),
    fetchedAt: hoursAgo(8),
    expiresAt: null,
  },
  {
    id: 9014,
    externalId: "demo-14",
    title: "Reclaimed Wood Floating Shelves — Set of 3",
    description:
      "Hand-finished reclaimed barn wood shelves with hidden brackets included.",
    url: "#",
    imageUrl: null,
    price: 89.0,
    originalPrice: 120.0,
    store: "Salvage One",
    source: "Demo",
    category: "retail",
    isBigBox: false,
    isChicagoland: true,
    publishedAt: hoursAgo(9),
    fetchedAt: hoursAgo(9),
    expiresAt: null,
  },
  {
    id: 9021,
    externalId: "demo-21",
    title: "Tire Rotation + Balance — $29.99 Any Vehicle",
    description:
      "Four-tire rotation, balance, and pressure check. No appointment needed.",
    url: "#",
    imageUrl: null,
    price: 29.99,
    originalPrice: 49.99,
    store: "Quick Lane Tire & Auto",
    source: "Demo",
    category: "auto-service",
    isBigBox: false,
    isChicagoland: false,
    publishedAt: hoursAgo(9),
    fetchedAt: hoursAgo(9),
    expiresAt: null,
  },
  {
    id: 9015,
    externalId: "demo-15",
    title: "Organic Dog Treats — Buy 2 Bags Get 1 Free",
    description:
      "Locally baked organic treats made with peanut butter and pumpkin. Dogs love them.",
    url: "#",
    imageUrl: null,
    price: 18.0,
    originalPrice: 27.0,
    store: "Fido & Co Pet Shop",
    source: "Demo",
    category: "retail",
    isBigBox: false,
    isChicagoland: true,
    publishedAt: hoursAgo(10),
    fetchedAt: hoursAgo(10),
    expiresAt: null,
  },
  {
    id: 9016,
    externalId: "demo-16",
    title: "Hand-Poured Chocolate Truffles — Gift Box $15",
    description:
      "Assorted flavors including espresso, lavender, and sea salt caramel. 12-piece box.",
    url: "#",
    imageUrl: null,
    price: 15.0,
    originalPrice: 22.0,
    store: "Sweet Spot Chocolates",
    source: "Demo",
    category: "retail",
    isBigBox: false,
    isChicagoland: true,
    publishedAt: hoursAgo(11),
    fetchedAt: hoursAgo(11),
    expiresAt: null,
  },
  {
    id: 9017,
    externalId: "demo-17",
    title: "Stainless Steel Water Bottle — Custom Engraving Included",
    description:
      "32oz double-wall insulated bottle with free custom engraving this week only.",
    url: "#",
    imageUrl: null,
    price: 28.0,
    originalPrice: 40.0,
    store: "The Engrave Shop",
    source: "Demo",
    category: "retail",
    isBigBox: false,
    isChicagoland: false,
    publishedAt: hoursAgo(12),
    fetchedAt: hoursAgo(12),
    expiresAt: null,
  },
  {
    id: 9022,
    externalId: "demo-22",
    title: "Windshield Chip Repair — Free with Insurance",
    description:
      "Most insurance covers chip repair with zero deductible. Walk-ins welcome.",
    url: "#",
    imageUrl: null,
    price: 0,
    originalPrice: 75.0,
    store: "SafeGlass Auto",
    source: "Demo",
    category: "auto-service",
    isBigBox: false,
    isChicagoland: false,
    publishedAt: hoursAgo(13),
    fetchedAt: hoursAgo(13),
    expiresAt: null,
  },
  {
    id: 9023,
    externalId: "demo-23",
    title: "Car Detailing Package — Interior + Exterior $119",
    description:
      "Hand wash, clay bar, wax, interior vacuum, leather conditioning, and window cleaning.",
    url: "#",
    imageUrl: null,
    price: 119.0,
    originalPrice: 189.0,
    store: "Prestige Detail Studio",
    source: "Demo",
    category: "auto-service",
    isBigBox: false,
    isChicagoland: true,
    publishedAt: hoursAgo(14),
    fetchedAt: hoursAgo(14),
    expiresAt: null,
  },
  {
    id: 9024,
    externalId: "demo-24",
    title: "Houseplant Sale — All Pothos & Philodendrons 30% Off",
    description:
      "Huge selection of easy-care houseplants. Pots and soil also on sale.",
    url: "#",
    imageUrl: null,
    price: null,
    originalPrice: null,
    store: "Sprout Home",
    source: "Demo",
    category: "retail",
    isBigBox: false,
    isChicagoland: true,
    publishedAt: hoursAgo(15),
    fetchedAt: hoursAgo(15),
    expiresAt: null,
  },
  {
    id: 9025,
    externalId: "demo-25",
    title: "Bluetooth Mechanical Keyboard — Hot-Swap Switches",
    description:
      "75% layout with hot-swappable switches and RGB. Great entry-level mech keyboard.",
    url: "#",
    imageUrl: null,
    price: 54.99,
    originalPrice: 79.99,
    store: "MechKeys Direct",
    source: "Demo",
    category: "retail",
    isBigBox: false,
    isChicagoland: false,
    publishedAt: hoursAgo(16),
    fetchedAt: hoursAgo(16),
    expiresAt: null,
  },
];
